# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeffrey/Documents/Prog_Avance_Fight_game/build

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeffrey/Documents/Prog_Avance_Fight_game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeffrey/Documents/Prog_Avance_Fight_game/CMakeFiles /home/jeffrey/Documents/Prog_Avance_Fight_game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeffrey/Documents/Prog_Avance_Fight_game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

controller/controller.o: controller/controller.c.o
.PHONY : controller/controller.o

# target to build an object file
controller/controller.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/controller/controller.c.o
.PHONY : controller/controller.c.o

controller/controller.i: controller/controller.c.i
.PHONY : controller/controller.i

# target to preprocess a source file
controller/controller.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/controller/controller.c.i
.PHONY : controller/controller.c.i

controller/controller.s: controller/controller.c.s
.PHONY : controller/controller.s

# target to generate assembly for a file
controller/controller.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/controller/controller.c.s
.PHONY : controller/controller.c.s

data/data.o: data/data.c.o
.PHONY : data/data.o

# target to build an object file
data/data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/data/data.c.o
.PHONY : data/data.c.o

data/data.i: data/data.c.i
.PHONY : data/data.i

# target to preprocess a source file
data/data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/data/data.c.i
.PHONY : data/data.c.i

data/data.s: data/data.c.s
.PHONY : data/data.s

# target to generate assembly for a file
data/data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/data/data.c.s
.PHONY : data/data.c.s

graphics/graphics.o: graphics/graphics.c.o
.PHONY : graphics/graphics.o

# target to build an object file
graphics/graphics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/graphics/graphics.c.o
.PHONY : graphics/graphics.c.o

graphics/graphics.i: graphics/graphics.c.i
.PHONY : graphics/graphics.i

# target to preprocess a source file
graphics/graphics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/graphics/graphics.c.i
.PHONY : graphics/graphics.c.i

graphics/graphics.s: graphics/graphics.c.s
.PHONY : graphics/graphics.s

# target to generate assembly for a file
graphics/graphics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/graphics/graphics.c.s
.PHONY : graphics/graphics.c.s

hits/hits.o: hits/hits.c.o
.PHONY : hits/hits.o

# target to build an object file
hits/hits.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/hits/hits.c.o
.PHONY : hits/hits.c.o

hits/hits.i: hits/hits.c.i
.PHONY : hits/hits.i

# target to preprocess a source file
hits/hits.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/hits/hits.c.i
.PHONY : hits/hits.c.i

hits/hits.s: hits/hits.c.s
.PHONY : hits/hits.s

# target to generate assembly for a file
hits/hits.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/hits/hits.c.s
.PHONY : hits/hits.c.s

init/init.o: init/init.c.o
.PHONY : init/init.o

# target to build an object file
init/init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/init/init.c.o
.PHONY : init/init.c.o

init/init.i: init/init.c.i
.PHONY : init/init.i

# target to preprocess a source file
init/init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/init/init.c.i
.PHONY : init/init.c.i

init/init.s: init/init.c.s
.PHONY : init/init.s

# target to generate assembly for a file
init/init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/init/init.c.s
.PHONY : init/init.c.s

liste/liste.o: liste/liste.c.o
.PHONY : liste/liste.o

# target to build an object file
liste/liste.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/liste/liste.c.o
.PHONY : liste/liste.c.o

liste/liste.i: liste/liste.c.i
.PHONY : liste/liste.i

# target to preprocess a source file
liste/liste.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/liste/liste.c.i
.PHONY : liste/liste.c.i

liste/liste.s: liste/liste.c.s
.PHONY : liste/liste.s

# target to generate assembly for a file
liste/liste.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/liste/liste.c.s
.PHONY : liste/liste.c.s

lootbox/lootbox.o: lootbox/lootbox.c.o
.PHONY : lootbox/lootbox.o

# target to build an object file
lootbox/lootbox.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lootbox/lootbox.c.o
.PHONY : lootbox/lootbox.c.o

lootbox/lootbox.i: lootbox/lootbox.c.i
.PHONY : lootbox/lootbox.i

# target to preprocess a source file
lootbox/lootbox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lootbox/lootbox.c.i
.PHONY : lootbox/lootbox.c.i

lootbox/lootbox.s: lootbox/lootbox.c.s
.PHONY : lootbox/lootbox.s

# target to generate assembly for a file
lootbox/lootbox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/lootbox/lootbox.c.s
.PHONY : lootbox/lootbox.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

movements/movements.o: movements/movements.c.o
.PHONY : movements/movements.o

# target to build an object file
movements/movements.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/movements/movements.c.o
.PHONY : movements/movements.c.o

movements/movements.i: movements/movements.c.i
.PHONY : movements/movements.i

# target to preprocess a source file
movements/movements.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/movements/movements.c.i
.PHONY : movements/movements.c.i

movements/movements.s: movements/movements.c.s
.PHONY : movements/movements.s

# target to generate assembly for a file
movements/movements.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/movements/movements.c.s
.PHONY : movements/movements.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... controller/controller.o"
	@echo "... controller/controller.i"
	@echo "... controller/controller.s"
	@echo "... data/data.o"
	@echo "... data/data.i"
	@echo "... data/data.s"
	@echo "... graphics/graphics.o"
	@echo "... graphics/graphics.i"
	@echo "... graphics/graphics.s"
	@echo "... hits/hits.o"
	@echo "... hits/hits.i"
	@echo "... hits/hits.s"
	@echo "... init/init.o"
	@echo "... init/init.i"
	@echo "... init/init.s"
	@echo "... liste/liste.o"
	@echo "... liste/liste.i"
	@echo "... liste/liste.s"
	@echo "... lootbox/lootbox.o"
	@echo "... lootbox/lootbox.i"
	@echo "... lootbox/lootbox.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... movements/movements.o"
	@echo "... movements/movements.i"
	@echo "... movements/movements.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

